config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'events/index'

  get 'events/show'

  get 'events/new'

  get 'events/edit'

  get 'events/create'

  get 'events/update'

  get 'events/destroy'

  get 'announcements/new'

  get 'friends/index'

  get 'friends/destroy'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  put '/logout', to: 'sessions#destroy'

  #custom routes for API requests
  post '/api/login', to: 'api/authentication#authenticate'

  get '/api/events', to: 'api/events#index'

  get '/api/events/:id', to: 'api/events#show'

  get 'api/users/:id', to: 'api/users#show'

  resources :announcements
  resources :events
  resources :groups
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  before_save {self.mail = mail.downcase}

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :mail, presence: true, uniqueness: { case_sensitive: false }, format: {with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, allow_blank: true }
  validates :password, length: { minimum: 8 }, allow_nil: true

  has_many :user_relationships
  has_many :group_memberships
  has_many :groups, through: :group_memberships

end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController

  def show
    @user = User.find(params[:id])
    render json: @user, except: [:is_admin, :created_at, :updated_at, :password_digest]
  end

  private

  def event_params
    params.require(:event).permit(:id, :name, :description, :date, locations_attributes: [:id, :name, :lat, :long])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id, :last_name, :first_name, :mail, :password, :is_admin, :group_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :first_name, class: "control-label col-sm-4" %>
    <div class="col-sm-6">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :last_name, class: "control-label col-sm-4" %>
    <div class="col-sm-6">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :mail, class: "control-label col-sm-4" %>
    <div class="col-sm-6">
      <%= f.text_field :mail, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :password, class: "control-label col-sm-4" %>
    <div class="col-sm-6">
      <%= f.text_field :password, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :is_admin, class: "control-label col-sm-4" %>
    <div class="col-sm-6">
      <%= f.check_box :is_admin, class: "form-control" %>
    </div>
  </div>

  <div class="ln_solid"></div>
  <div class="">
    <%= link_to "Cancel", users_path, class: "btn btn-danger" %>
    <%= submit_tag "Submit", class: "btn btn-success pull-right"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body">

        <%= render 'form', user: @user %>

      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Users</h3>
  </div>
  <div class="title_right">
    <div class="btn-toolbar pull-right">
      <%= link_to 'New User', new_user_path,class: "btn btn-default" %>
    </div>
  </div>
</div>

<div class="clearfix"></div>
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
    <% if @users.any? %>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th width="10%">ID</th>
            <th width="20%">Name</th>
            <th width="30%">E-Mail</th>
            <th width="20%">Admin</th>
            <th width="20%">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.first_name %> <%= user.last_name %></td>
              <td><%= user.mail %></td>
              <td><%= user.is_admin %></td>
              <td>
                <div class="btn-toolbar">
                  <%= link_to 'Show', user, class: "btn btn-primary btn-xs" %>
                  <%= link_to 'Edit', edit_user_path(user), class: "btn btn-default btn-xs" %>
                  <%= link_to 'Destroy', user, class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body">

        <%= render 'form', user: @user %>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="page-title">
  <div class="title_left">
    <p class="text-muted">#<%= @user.id %>
      <% if @user.is_admin %>
        <span class="label label-success">Admin</span>
      <% end %>
    </p>
    <h3><%= @user.first_name %> <%= @user.last_name %></h3>
  </div>
  <div class="title_right">
    <div class="btn-toolbar pull-right">
      <%= link_to 'Back', users_path,class: "btn btn-primary" %>
      <%= link_to 'Edit', edit_user_path(@user),class: "btn btn-default" %>
    </div>
  </div>
</div>

<div class="clearfix"></div>
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body eliminate-last-margin">
        <div class="row">
          <div class="col-xs-12">
            <dl class="dl-horizontal">
              <dt>First Name</dt>
              <dd><%= @user.first_name %></dd>
              <dt>Last Name</dt>
              <dd><%= @user.last_name %></dd>
              <dt>E-Mail</dt>
              <dd><%= @user.mail %></dd>
              <dt>Role</dt>
              <% if @user.is_admin %>
                <dd>Admin</dd>
                <% else %>
                <dd>User</dd>
              <% end %>
            </dl>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>