config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'events/index'

  get 'events/show'

  get 'events/new'

  get 'events/edit'

  get 'events/create'

  get 'events/update'

  get 'events/destroy'

  get 'announcements/new'

  get 'friends/index'

  get 'friends/destroy'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  put '/logout', to: 'sessions#destroy'

  #custom routes for API requests
  post '/api/login', to: 'api/authentication#authenticate'

  get '/api/events', to: 'api/events#index'

  get '/api/events/:id', to: 'api/events#show'

  get 'api/users/:id', to: 'api/users#show'

  resources :announcements
  resources :events
  resources :groups
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true

  has_many :locations, :autosave => true
  has_many :announcements

  accepts_nested_attributes_for :locations, :allow_destroy => true, :reject_if => :all_blank

end

app/controllers/api/events_controller.rb
class Api::EventsController < Api::BaseController

  def index
    @events = Event.all
    render json: @events
  end

  def show
    @event = Event.find(params[:id])
    @announcements = Announcement.where(:event_id => params[:id]).reverse
    render json: {event: @event, announcements: @announcements}, except: [:created_at, :updated_at]
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
    @announcements = Announcement.where(:event_id => params[:id]).reverse
  end

  def new
    @event = Event.new
    @event.locations.build
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:id, :name, :description, :date, locations_attributes: [:id, :name, :lat, :long])
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def setup_event(event)
    event.locations ||= Location.new
    3.times { event.locations.build }
    event
  end
end

app/views/events/_form.html.erb
<%= form_for (setup_event(event)) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2>Information</h2>
  <div class="form-group row">
    <%= f.label :name, class: "control-label col-xs-4" %>
    <div class="col-xs-6">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :description, class: "control-label col-xs-4" %>
    <div class="col-xs-6">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :date, class: "control-label col-xs-4" %>
    <div class="col-xs-6">
      <%= f.datetime_select :date, class: "form-control" %>
    </div>
  </div>
  <h2>Locations</h2>
  <%= f.fields_for :locations do |ff| %>
    <div class="form-group row">
      <%= ff.label :name, class: "control-label col-xs-4" %>
      <div class="col-xs-6">
        <%= ff.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= ff.label :lat, class: "control-label col-xs-4" %>
      <div class="col-xs-6">
        <%= ff.number_field :lat, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= ff.label :long, class: "control-label col-xs-4" %>
      <div class="col-xs-6">
        <%= ff.number_field :long, class: "form-control" %>
      </div>
    </div>
  <% end %>
  <div class="ln_solid"></div>
  <div class="">
    <%= link_to "Cancel", events_path, class: "btn btn-danger" %>
    <%= submit_tag "Submit", class: "btn btn-success pull-right"%>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body">

        <%= render 'form', event: @event %>

      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Events</h3>
  </div>
  <div class="title_right">
    <div class="btn-toolbar pull-right">
      <%= link_to 'New Event', new_event_path,class: "btn btn-default" %>
    </div>
  </div>
</div>

<div class="clearfix"></div>
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
    <% if @events.any? %>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th width="10%">ID</th>
            <th width="20%">Name</th>
            <th width="30%">Description</th>
            <th width="20%">Date</th>
            <th width="20%">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td><%= event.id %></td>
              <td><%= event.name %></td>
              <td><%= event.description %></td>
              <td><%= event.date %></td>
              <td>
                <div class="btn-toolbar">
                  <%= link_to 'Show', event, class: "btn btn-primary btn-xs" %>
                  <%= link_to 'Edit', edit_event_path(event), class: "btn btn-default btn-xs" %>
                  <%= link_to 'Destroy', event, class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body">


        <%= render 'form', event: @event %>

      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="page-title">
  <div class="title_left">
    <p class="text-muted">#<%= @event.id %></p>
    <h3><%= @event.name %></h3>
  </div>
  <div class="title_right">
    <div class="btn-toolbar pull-right">
      <%= link_to 'Back', events_path,class: "btn btn-primary" %>
      <%= link_to 'Edit', edit_event_path(@event),class: "btn btn-default" %>
      <%= link_to 'New Announcement', announcements_new_path(event_id: @event),class: "btn btn-default" %>
    </div>
  </div>
</div>

<div class="clearfix"></div>
<div class="col-xs-12">
  <div class="panel panel-default">
    <div class="panel-body eliminate-last-margin">

      <div class="row">
        <div class="col-xs-12">
          <h2>Information</h2>
          <dl class="dl-vertical">
              <dt>Name</dt>
              <dd><%= @event.name %></dd>
              <br>
              <dt>Date</dt>
              <dd><%= @event.date %></dd>
              <br>
              <dt>Description</dt>
              <dd><%= @event.description %></dd>
              <br>
              <dt>Locations</dt>
              <dd>
                <% if @event.locations %>
                  <% @event.locations.each do |location|%>
                    <%= location.name %> |
                  <% end %>
                <% end %>
              </dd>
          </dl>
        </div>
      </div>

      <div class="clearfix"></div>
      <div class="row">
        <div class="col-xs-12">
          <h2>Locations</h2>
          <div id="event-map">

          </div>
          <script type="text/javascript">
            <%= @event.id%>
            initMap();
          </script>
        </div>
      </div>


      <div class="clearfix"></div>
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
          <h2>Announcements</h2>
          <% if @announcements.any? %>
            <% @announcements.each do |announcement| %>
            <div class="col-xs-12">
              <% if announcement.promotion %>
                <div class="x_panel" style="background-color: #1abb9c42;">
              <% else %>
                <div class="x_panel">
              <% end %>
                <div class="x_content">
                  <div class="btn-toolbar pull-right">
                    <%= link_to announcement_path(id: announcement.id, event_id: @event), class: 'btn btn-xs btn-danger', method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="fa fa-trash"></i>
                    <% end %>
                    <%= link_to edit_announcement_path(announcement.id), class: "btn btn-xs btn-primary" do %>
                      <i class="fa fa-wrench"></i>
                    <% end %>
                  </div>
                  <h2><%= announcement.name %></h2>
                  <span><%= announcement.description %></span>
                </div>
                </div>
            </div>
          <% end %>
        <% end %>
        </div>
      </div>


    </div>
  </div>
</div>