config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'events/index'

  get 'events/show'

  get 'events/new'

  get 'events/edit'

  get 'events/create'

  get 'events/update'

  get 'events/destroy'

  get 'announcements/new'

  get 'friends/index'

  get 'friends/destroy'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  put '/logout', to: 'sessions#destroy'

  #custom routes for API requests
  post '/api/login', to: 'api/authentication#authenticate'

  get '/api/events', to: 'api/events#index'

  get '/api/events/:id', to: 'api/events#show'

  get 'api/users/:id', to: 'api/users#show'

  resources :announcements
  resources :events
  resources :groups
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Festival</title>
    <meta name="charset" content="utf8">
    <meta name="robots" content="noindex,follow">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= yield :head%>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">

        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">

            <div class="navbar nav_title" style="border: 0;">
              <a href="/" class="site_title"><span><%= image_tag("logo.png", width: "70%") %></span></a>
            </div>

            <div class="clearfix"></div>

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">

                <ul class="nav side-menu">
                  <li>
                    <a href="/"><i class="glyphicon glyphicon-home"></i>Home</a>
                    <!-- <ul class="nav child_menu" style="display: none;">
                      <li>
                        <a href="/">NEW</a>
                      </li>
                    </ul> -->
                  </li>

                  <li>
                    <%= link_to events_path do %>
                      <i class="glyphicon glyphicon-calendar"></i> Events
                    <% end %>
                  </li>

                  <li>
                    <%= link_to users_path do %>
                      <i class="glyphicon glyphicon-user"></i> Users
                    <% end %>
                  </li>
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav role="navigation">
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img width="29" height="29" src="<%= asset_path("user.png") %>">
                    <%= current_user.first_name %> <%= current_user.last_name %>
                    <span class="fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu animated fadeInDown pull-right">
                    <li>
                      <%= link_to user_path(current_user) do %>
                        <i class="fa fa-user pull-right"></i> Profile
                      <% end %>
                    </li>
                    <li>
                      <%= link_to logout_path, method: :put do %>
                        <i class="fa fa-sign-out pull-right"></i> Log Out
                      <% end %>
                    </li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->
        <!-- page content -->
        <div class="right_col" role="main" style="min-height: 650px;">
            <div>
              <% if flash[:alert].present? %>
                <div class="row">
                  <div class="col-lg-12">
                    <div class="alert alert-danger">
                      <%= flash[:alert] %>
                    </div>
                  </div>
                </div>
              <% end %>
              <% if flash[:notice].present? %>
                <div class="row">
                  <div class="col-lg-12">
                    <div class="alert alert-success">
                      <%= flash[:notice] %>
                    </div>
                  </div>
                </div>
              <% end %>
              <%= yield %>
            </div>
        </div>
        <!-- /page content -->
        <!-- footer content -->
        <footer>
            <div class="pull-right">
              Copyright <%= Time.now.year %> by <a href="/" target="_blank">Festival</a>
            </div>
            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>
    <%= javascript_include_tag 'gentelella' %>
    <%= javascript_include_tag 'gentelella-custom' %>
  </body>
</html>